# Generated by Django 5.1.4 on 2025-05-14 14:57

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='nom utilisateur membre')),
                ('is_staff', models.BooleanField(default=False)),
                ('commission', models.CharField(choices=[('Partenariat', 'partenariat'), ('Personne', 'personne'), ('Prosperité', 'prosperité'), ('Planète', 'Planète'), ('paix', 'paix')], max_length=255)),
                ('fonction', models.CharField(choices=[('Coodonateur', 'coodonateur'), ('Chef de commission', 'Chef de commission'), ('Chef adjoint commission', 'Chef adjoint commission'), ('Membre', 'Membre')], max_length=155)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField()),
                ('begin', models.DateTimeField(verbose_name='Date debut')),
                ('end', models.DateTimeField(verbose_name='date final')),
                ('rapport', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('member', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
