# Generated by Django 5.1.4 on 2025-05-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activité'},
        ),
        migrations.AlterModelOptions(
            name='memberuser',
            options={'verbose_name': 'Membre utilisateur'},
        ),
        migrations.AddField(
            model_name='activity',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
