# Generated by Django 5.1.4 on 2025-05-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0002_alter_activity_options_alter_memberuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='rapport',
            field=models.TextField(null=True),
        ),
    ]
