# Generated by Django 5.1.4 on 2025-05-19 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0003_alter_activity_rapport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='member',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
