# Generated by Django 5.1.4 on 2025-05-19 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0004_alter_activity_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='rapport',
            field=models.TextField(blank=True, null=True),
        ),
    ]
