# Generated by Django 5.1.4 on 2025-05-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0005_alter_activity_member_alter_activity_rapport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
