# Generated by Django 5.1.4 on 2025-04-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0006_alter_activity_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberuser',
            name='in_community',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberuser',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
