# Generated by Django 5.1.4 on 2025-04-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0008_infoout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoout',
            options={'ordering': ['-pk']},
        ),
    ]
